# Generated by Django 4.2.4 on 2023-08-31 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('apps_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('name', models.CharField(max_length=150)),
                ('semester', models.IntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Fall')])),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_user.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_course.studentcourseenrollment')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='apps_course.StudentCourseEnrollment', to='apps_user.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_user.teacher'),
        ),
    ]
